### ISSUE TITLE
Doesn't work with Grav v1.2.4

### ISSUE THREAD

**Issue by draeron** [Carve/grav-ui-libraries#5]
I'm new to grav but while trying out this plugin, i realised it wasn't working at all. This is probably the result of some changes in grav plugin architecture at some time. Anyhow the pluging's name is `ui-libraries` but the files are named `grav-ui-libraries.php` and `ui-libraries.php`. 

Result : the plugins doesn't load.
Fix : either rename the plugin or the files to match.

**Comment by Carve** [comment]
I will test it locally and remotely with Grav v1.2.4

**Comment by Carve** [comment]
I've went ahead and updated the repo with changes to the plugin files themselves and its' loading for me.  Please let me know if you run into further issues after Grav mirrors the update @draeron
